---
- name: Deploy Node.js App on Docker
  hosts: localhost
  tasks:
    - name: Build Docker Image
      community.docker.docker_image:
        name: simple-nodejs-app
        path: ../
        tag: latest

    - name: Run Docker Container
      community.docker.docker_container:
        name: simple-nodejs-app
        image: simple-nodejs-app:latest
        state: started
        ports:
          - "3000:3000"

